//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2159
        ///2527
        ///2441
        ///3299
        ///1672
        ///3025
        ///2820
        ///6821
        ///3201
        ///1204
        ///1208
        ///4861
        ///5621
        ///
        ///5580
        ///18071
        ///
        ///8803
        ///1667
        ///4173
        ///9404
        ///9718
        ///10311
        ///
        ///12237
        ///5068
        ///9824
        ///6535
        ///
        ///25484
        ///
        ///18598
        ///2851
        ///13577
        ///
        ///13719
        ///9147
        ///11204
        ///8554
        ///11796
        ///1297
        ///
        ///43055
        ///
        ///8156
        ///4616
        ///
        ///16383
        ///17036
        ///16017
        ///18569
        ///
        ///33581
        ///10017
        ///
        ///65566
        ///
        ///5750
        ///6961
        ///4494
        ///11117
        ///3392
        ///10471
        ///3490
        ///
        ///7006
        ///7526
        ///9302
        ///1454
        ///4039
        ///8067
        ///9321
        ///8888
        ///7380
        ///
        ///8543
        ///2106
        ///2986
        ///3465
        ///9592
        ///11240
        ///1795
        ///
        ///4396
        ///27967
        ///
        ///8091
        ///19515
        ///1282
        ///
        ///6241
        ///8946
        ///6665
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
    }
}
