//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day4.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-93,2-11
        ///26-94,26-94
        ///72-92,48-88
        ///36-37,37-52
        ///2-98,1-98
        ///1-83,1-84
        ///74-79,76-76
        ///66-85,66-86
        ///6-73,6-73
        ///31-57,30-58
        ///1-98,1-98
        ///28-47,55-97
        ///29-71,70-72
        ///40-53,40-53
        ///14-71,39-71
        ///19-98,18-94
        ///94-96,81-95
        ///79-98,79-97
        ///52-66,60-61
        ///2-3,8-89
        ///53-59,59-83
        ///79-81,3-80
        ///14-84,84-92
        ///90-90,7-89
        ///10-76,11-76
        ///9-31,10-12
        ///8-8,8-72
        ///2-97,1-96
        ///3-33,2-94
        ///3-5,4-99
        ///46-94,8-94
        ///97-98,14-92
        ///60-98,81-99
        ///11-98,11-97
        ///27-82,26-81
        ///21-61,12-18
        ///26-55,26-56
        ///89-96,97-97
        ///29-30,29-31
        ///66-90,40-87
        ///7-49,8-88
        ///37-61,39 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-4,6-8
        ///2-3,4-5
        ///5-7,7-9
        ///2-8,3-7
        ///6-6,4-6
        ///2-6,4-8.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
    }
}
